services:
  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  orchestrator:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 40s
    build: ./src/orchestrator
    container_name: orchestrator
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      VERBOSE: false
      LANGUAGE_CONTEXT_URL: http://language-context:8080/extract
      CODEBASE_CONTEXT_URL: http://codebase-context:8080/extract
      DEPLOYMENT_SUGGESTION_URL: http://deployment-suggestion:8080/suggest
      GENERATE_TERRAFORM_URL: http://generate-terraform:8080/terraform
      # CONTAINERIZE_URL: http://containerize-project:8080/
      # DEPLOY_URL: http://deploy-with-terraform:8007/
    command: bun --hot start
    develop:
      watch:
        - action: sync
          path: ./src/orchestrator/index.ts
          target: /app/index.ts
        - action: rebuild
          path: package.json

  language-context:
    build: ./src/services/language-context
    container_name: language-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/language-context/
          target: /app/
          ignore:
            - __pycache__/

  codebase-context:
    build: ./src/services/codebase-context
    container_name: codebase-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/codebase-context/
          target: /app/
          ignore:
            - __pycache__/

  deployment-suggestion:
    build: ./src/services/deployment-suggestion
    container_name: deployment-suggestion
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/deployment-suggestion/
          target: /app/
          ignore:
            - __pycache__/
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  
  generate-terraform:
    build: ./src/services/generate-terraform
    container_name: generate-terraform
    expose:
      - "8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./src/services/generate-terraform/
          target: /app/
          ignore:
            - __pycache__/
            - .venv/

  containerize-project:
    build: ./src/services/containerize-project
    container_name: containerize-project
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/containerize-project/
          target: /app/
          ignore:
            - __pycache__/


  deploy-with-terraform:
    build: ./src/services/deploy-with-terraform
    container_name: deploy-with-terraform
    expose:
      - "8080"