services:
  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    develop:
      watch:
        - action: sync
          path: ./src/frontend/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  orchestrator:
    build: ./src/orchestrator
    container_name: orchestrator
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      VERBOSE: false
      LANGUAGE_CONTEXT_URL: http://language-context:8080/extract
      CODEBASE_CONTEXT_URL: http://codebase-context:8080/extract
      DEPLOYMENT_SUGGESTION_URL: http://deployment-suggestion:8080/suggest
      CONTAINERIZE_URL: http://containerize-project:8080/
      CONTAINERIZATION_URL: http://containerization:8005/
      TERRAFORM_URL: http://generate-terraform:8006/
      DEPLOY_URL: http://deploy-with-terraform:8007/
    command: bun --hot start
    develop:
      watch:
        - action: sync
          path: ./src/orchestrator/index.ts
          target: /app/index.ts
        - action: rebuild
          path: package.json

  language-context:
    build: ./src/services/language-context
    container_name: language-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/language-context/
          target: /app/
          ignore:
            - __pycache__/

  codebase-context:
    build: ./src/services/codebase-context
    container_name: codebase-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/codebase-context/
          target: /app/
          ignore:
            - __pycache__/


  deployment-suggestion:
    build: ./src/services/deployment-suggestion
    container_name: deployment-suggestion
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/deployment-suggestion/
          target: /app/
          ignore:
            - __pycache__/
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  containerize-project:
    build: ./src/services/containerize-project
    container_name: containerize-project
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/services/containerize-project/
          target: /app/
          ignore:
            - __pycache__/

  containerization:
    build: ./src/services/containerization
    container_name: containerization
    expose:
      - "8005"
    networks:
      - internal

  generate-terraform:
    build: ./src/services/generate-terraform
    container_name: generate-terraform
    expose:
      - "8080"
    networks:
      - internal

  deploy-with-terraform:
    build: ./src/services/deploy-with-terraform
    container_name: deploy-with-terraform
    expose:
      - "8080"
    networks:
      - internal

networks:
  internal:
    driver: bridge