services:
  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - orchestrator
    networks:
      - internal

  orchestrator:
    build: ./src/orchestrator
    container_name: orchestrator
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      VERBOSE: false
      LANGUAGE_CONTEXT_URL: http://language-context:8080/extract
      CODEBASE_CONTEXT_URL: http://codebase-context:8080/extract
      SUGGESTION_URL: http://deployment-suggestion:8003/
      CONTAINERIZE_URL: http://containerize-project:8004/
      CONTAINERIZATION_URL: http://containerization:8005/
      TERRAFORM_URL: http://generate-terraform:8006/
      DEPLOY_URL: http://deploy-with-terraform:8007/
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  language-context:
    build: ./src/services/language-context
    container_name: language-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app/
          ignore:
            - __pycache__/

  codebase-context:
    build: ./src/services/codebase-context
    container_name: codebase-context
    expose:
      - "8080"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app/
          ignore:
            - __pycache__/


  deployment-suggestion:
    build: ./src/services/deployment-suggestion
    container_name: deployment-suggestion
    expose:
      - "8003"
    networks:
      - internal

  containerize-project:
    build: ./src/services/containerize-project
    container_name: containerize-project
    expose:
      - "8004"
    networks:
      - internal

  containerization:
    build: ./src/services/containerization
    container_name: containerization
    expose:
      - "8005"
    networks:
      - internal

  generate-terraform:
    build: ./src/services/generate-terraform
    container_name: generate-terraform
    expose:
      - "8006"
    networks:
      - internal

  deploy-with-terraform:
    build: ./src/services/deploy-with-terraform
    container_name: deploy-with-terraform
    expose:
      - "8007"
    networks:
      - internal

networks:
  internal:
    driver: bridge